image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
  tags:
    - trader-app

deploy:
  stage: deploy
  script:
    - ./bin/www
  tags:
    - trader-app